# Generated by Django 2.2.3 on 2019-07-21 18:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewlist',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='interviewlist',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 21, 23, 56, 1, 796666)),
        ),
        migrations.AlterField(
            model_name='interviewlist',
            name='interviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
