# Generated by Django 2.2.3 on 2019-07-22 04:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewlist',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 22, 10, 16, 56, 488256)),
        ),
    ]
