# Generated by Django 2.2.3 on 2019-07-24 02:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190724_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewlist',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 24, 8, 23, 56, 27322)),
        ),
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 24, 8, 23, 56, 28050)),
        ),
    ]
